version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - '/home/pedro/app1/postgres:/var/lib/postgresql/data'

  website:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
